[build]
  publish = "public"
  command = "gatsby build"
  NETLIFY_USE_YARN = "true"
[build.environment]
  NODE_VERSION = "14.17.1"
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
  output_path = "reports/lighthouse.html"
[[plugins]]
  package = "@netlify/plugin-gatsby"    
[[headers]]
  for = "/*"
  [headers.values]
    cache-control = '''
	  public,
	  max-age=2592000'''
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Robots-Tag = "index"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Access-Control-Allow-Origin = '''
      https://donboulton.com,
      https://graphql.fauna.com,
      https://graphql.fauna.com/graphql
      https://img.badgesize.io/, 
      https://www.unpkg.com/use-sound/dist/use-sound.esm.js.svg, 
      https://www.google-analytics.com/analytics.js,
      https://www.googletagmanager.com/gtag/js
      https://static.doubleclick.net, 
      https://cdn.viglink.com, 
      https://github.com, 
      https://bitbucket.status.atlassian.com, 
      https://links.services.disqus.com, 
      https://img.shields.io, 
      https://secure.gravatar.com, 
      https://identity.netlify.com, 
      https://media-library.cloudinary.com, 
      https://withspectrum.github.io, 
      https://cdn.rawgit.com https://api.bitbucket.org, 
      https://widget.cloudinary.com, 
      https://www.youtube.com, 
      https://www.youtube.de, 
      https://cdn.lr-ingest.io, 
      https://d33wubrfki0l68.cloudfront.net, 
      https://www.googletagmanager.com,
      https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js,
      https://i.ytimg.com, 
      https://fonts.gstatic.com, 
      https://d33wubrfki0l68.cloudfront.net/0bd90e5ef8c6650f6ecc41a11a46d3f66e5a898e/dd6a2/static/roboto-latin-100-a45108d3b34af91f9113d827a183296d.woff
      https://d33wubrfki0l68.cloudfront.net/7d02b9455622a72bfc55a938a3e6bcccfcd57d0e/0abce/static/roboto-latin-100-c2aa4ab115bf9c6057cb59709d0e152b.woff2
      https://www.google-analytics.com, 
      https://storage.googleapis.com, 
      https://yt3.ggpht.com, 
      https://ocsp.digicert.com, 
      https://graph.facebook.com, 
      https://api.tumblr.com, 
      https://www.reddit.com, 
      https://googleads.g.doubleclick.net, 
      https://static.doubleclick.net, 
      https://api.applause-button.com, 
      https://apis.google.com, 
      https://r.lr-ingest.io, 
      https://connect.facebook.net, 
      https://res.cloudinary.com, 
      https://i.ytimg.com,
      https://api.github.com
      https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
      https://stats.g.doubleclick.net/
      https://www.google.com/recaptcha/api.js
      https://static.small.chat/messenger.js
      https://www.gstatic.com/recaptcha/releases/kcXVPRWG7fMILHmzon0--fD3/recaptcha__en.js
    '''      
    Access-Control-Allow-Methods = '''
      POST, 
      GET,
      PUT,  
      DELETE,
      HEAD
    '''
    Access-Control-Allow-Credentials = "true"
    Vary = "Accept-Encoding"
    Permissions-Policy = '''
      accelerometer=(self),
      ambient-light-sensor=(self),
      autoplay=(self),
      camera=(self),
      encrypted-media=(self),
      fullscreen=(self),
      geolocation=(self),
      gyroscope=(self),
      magnetometer=(self),
      microphone=(self),
      midi=(self),
      payment=(self),
      picture-in-picture=(self),
      speaker=(self),
      usb=(self),
      vibrate=(self),
      vr=(self)
    '''
    Content-Security-Policy = "connect-src 'self' blob: https://d33wubrfki0l68.cloudfront.net/170d8b39e0b2a3545f692b77308183f23aa95619/f64bd/static/bg-dd64ddf5e80e93408160f381114eb4e8.jpg https://donboulton.com https://www.googletagmanager.com/gtag/js https://www.google.com/recaptcha/api.js https://embed.small.chat/T8PMJ5ZNYGDRA9BJEA.js https://www.gstatic.com/recaptcha/releases/kcXVPRWG7fMILHmzon0--fD3/recaptcha__en.js https://static.small.chat/messenger.js https://static.small.chat/messenger.css https://stats.g.doubleclick.net/ https://upload-widget.cloudinary.com/1.32.6/global/all.js https://www.gstatic.com/recaptcha/releases/Q_rrUPkK1sXoHi4wbuDTgcQR/recaptcha__en.js https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js https://img.badgesize.io/ https://www.unpkg.com/use-sound/dist/use-sound.esm.js.svg https://www.google-analytics.com/analytics.js https://static.doubleclick.net https://cdn.viglink.com https://github.com https://bitbucket.status.atlassian.com https://links.services.disqus.com https://img.shields.io https://secure.gravatar.com https://identity.netlify.com https://media-library.cloudinary.com https://withspectrum.github.io https://cdn.rawgit.com https://api.bitbucket.org https://widget.cloudinary.com https://www.youtube.com https://www.youtube.de https://donboulton.com https://c.disquscdn.com https://cdn.lr-ingest.io https://www.googletagmanager.com https://i.ytimg.com https://fonts.gstatic.com https://www.google-analytics.com https://storage.googleapis.com https://yt3.ggpht.com https://ocsp.digicert.com https://graph.facebook.com https://api.tumblr.com https://www.reddit.com https://googleads.g.doubleclick.net https://static.doubleclick.net https://api.applause-button.com https://apis.google.com https://r.lr-ingest.io https://connect.facebook.net https://res.cloudinary.com https://i.ytimg.com https://api.github.com https://fonts.gstatic.com https://graph.facebook.com https://api.tumblr.com https://www.reddit.com https://googleads.g.doubleclick.net https://apis.google.com https://www.google.com https://2y3o9lstgx-dsn.algolia.net https://2y3o9lstgx-1.algolianet.com https://2y3o9lstgx-2.algolianet.com https://2y3o9lstgx-3.algolianet.com https://yt3.ggpht.com https://ocsp.digicert.com https://cdn.lr-ingest.io https://r.lr-ingest.io https://static.doubleclick.netyt3.ggpht.com https://static.doubleclick.netcdn.lr-ingest.io https://graphql.fauna.com/graphql; form-action 'self' https://graphql.fauna.com https://netlify.com https://twitter.com https://*.twitter.com; font-src 'self' blob: data: https://d33wubrfki0l68.cloudfront.net/0bd90e5ef8c6650f6ecc41a11a46d3f66e5a898e/dd6a2/static/roboto-latin-100-a45108d3b34af91f9113d827a183296d.woff https://d33wubrfki0l68.cloudfront.net/7d02b9455622a72bfc55a938a3e6bcccfcd57d0e/0abce/static/roboto-latin-100-c2aa4ab115bf9c6057cb59709d0e152b.woff2 https://fonts.gstatic.com; frame-src 'self' https://www.google.com/ https://unpkg.com https://disqus.com https://cloudinary.com https://www.youtube.com https://twitter.com https://mobile.twitter.com https://pay.twitter.com https://cards-frame.twitter.com https://widget.cloudinary.com; img-src 'self' blob: data: https://d33wubrfki0l68.cloudfront.net/170d8b39e0b2a3545f692b77308183f23aa95619/f64bd/static/bg-dd64ddf5e80e93408160f381114eb4e8.jpg https://img.badgesize.io/ https://www.unpkg.com/use-sound/dist/use-sound.esm.js.svg https://badgen.net/bundlephobia/minzip/react-hook-form https://cdn.viglink.com https://secure.gravatar.com https://res.cloudinary.com https://referrer.disqus.com https://img.shields.io https://avatars0.githubusercontent.com https://avatars1.githubusercontent.com https://avatars2.githubusercontent.com https://cdn.rawgit.com https://withspectrum.github.io https://api.netlify.com https://widget.cloudinary.com https://static.doubleclick.net https://*.cdn.twitter.com https://ton.twitter.com https://*.twimg.com https://analytics.twitter.com https://cm.g.doubleclick.net https://www.google-analytics.com https://www.periscope.tv https://www.pscp.tv https://media.riffsy.com https://*.giphy.com https://*.pscp.tv https://platform-lookaside.fbsbx.com https://scontent.xx.fbcdn.net https://*.googleusercontent.com https://c.disquscdn.com https://links.services.disqus.com; manifest-src 'self'; media-src 'self' blob: https://res.cloudinary.com https://widget.cloudinary.com https://static.doubleclick.net https://www.youtube.com https://twitter.com https://*.twimg.com https://*.vine.co https://*.giphy.com https://dwo3ckksxlb0v.cloudfront.net; object-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://api.bitbucket.org https://secure.gravatar.com https://media-library.cloudinary.com https://graphql.fauna.com https://graphql.fauna.com/graphql https://mansbooks-1.disqus.com https://api.applause-button.com https://api.netlify.com https://netlify.com https://res.cloudinary.com https://www.google-analytics.com https://platform.slack-edge.com https://static.doubleclick.net https://widget.cloudinary.com https://www.youtube.com https://www.youtube.de https://twitter.com https://*.twimg.com https://www.google-analytics.com https://www.googletagmanager.com; script-src-elem 'self' blob: 'unsafe-inline' https://www.gstatic.com/recaptcha/releases/kcXVPRWG7fMILHmzon0--fD3/recaptcha__en.js https://www.google.com/recaptcha/api.js https://embed.small.chat/T8PMJ5ZNYGDRA9BJEA.js https://static.small.chat/messenger.js https://donboulton.us4.list-manage.com/* https://storage.googleapis.com https://github.com https://cdn.lr-ingest.io https://www.googletagmanager.com https://www.google-analytics.com https://api.applause-button.com https://api.netlify.com https://app.logrocket.com https://api.logrocket.com https://mansbooks-1.disqus.com https://c.disquscdn.com https://www.youtube.com https://media-library.cloudinary.com https://widget.cloudinary.com; style-src 'self' 'unsafe-inline' https://static.small.chat/messenger.css https://github.com https://api.bitbucket.org https://secure.gravatar.com https://media-library.cloudinary.com https://identity.netlify.com https://res.cloudinary.com https://static.doubleclick.net https://widget.cloudinary.com https://www.youtube.com https://youtube.de https://twitter.com https://*.twimg.com; prefetch-src 'self' blob: https://www.gstatic.com/recaptcha/releases/kcXVPRWG7fMILHmzon0--fD3/recaptcha__en.js https://static.small.chat/messenger.css https://www.google-analytics.com/analytics.js https://www.googletagmanager.com/gtag/js;  worker-src 'self' blob: https://www.googletagmanager.com/gtag/js https://storage.googleapis.com https://www.google-analytics.com/analytics.js; report-uri https://donboulton.report-uri.com/r/d/csp/reportOnly"
[[headers]]
  for = "/static/*"
  [headers.values]
    cache-control = '''
	  public,
	  max-age=31536000'''